#pragma once

#define SETTINGS_SERIAL_BAUD_RATE 500000

#define SETTINGS_MOTION_THRESH  5.0

#define SETTINGS_ARMED_TICK_COUNT 5

#define SETTINGS_ARMED_TICK_TIME 320

#define SETTINGS_ARM_TICK_COUNT 4

#define SETTINGS_ARM_TIME_THRESH 150

#define SETTINGS_ARM_TICK_TIME 500

#define SETTINGS_INIT_STEP_TIME 325 // ms

#define SETTINGS_INIT_NUM_STEPS 3

#define SETTINGS_MAX_MSG_LEN    32
